-- SQLite schema for the World Cup 2026 game.
-- Run as a single script via better-sqlite3's Database.exec().

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS groups_table (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS teams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  group_name TEXT NOT NULL,
  primary_color TEXT NOT NULL DEFAULT '#FFFFFF',
  secondary_color TEXT NOT NULL DEFAULT '#000000',
  confederation TEXT NOT NULL DEFAULT 'UEFA',
  flag_emoji TEXT NOT NULL DEFAULT '🏳️',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS players (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  team_id INTEGER NOT NULL,
  position TEXT NOT NULL CHECK (position IN ('GK','DEF','MID','FWD')),
  shirt_number INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS matches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_a INTEGER NOT NULL,
  team_b INTEGER NOT NULL,
  score_a INTEGER NOT NULL DEFAULT 0,
  score_b INTEGER NOT NULL DEFAULT 0,
  stage TEXT NOT NULL DEFAULT 'group' CHECK (stage IN ('group','knockout')),
  round_name TEXT DEFAULT NULL,
  played INTEGER NOT NULL DEFAULT 0,
  extra_time INTEGER NOT NULL DEFAULT 0,
  penalties INTEGER NOT NULL DEFAULT 0,
  penalty_score_a INTEGER DEFAULT NULL,
  penalty_score_b INTEGER DEFAULT NULL,
  match_order INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (team_a) REFERENCES teams(id),
  FOREIGN KEY (team_b) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS standings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  group_name TEXT NOT NULL,
  team_id INTEGER NOT NULL,
  points INTEGER NOT NULL DEFAULT 0,
  played INTEGER NOT NULL DEFAULT 0,
  won INTEGER NOT NULL DEFAULT 0,
  drawn INTEGER NOT NULL DEFAULT 0,
  lost INTEGER NOT NULL DEFAULT 0,
  goals_for INTEGER NOT NULL DEFAULT 0,
  goals_against INTEGER NOT NULL DEFAULT 0,
  goal_difference INTEGER GENERATED ALWAYS AS (goals_for - goals_against) STORED,
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  UNIQUE (group_name, team_id)
);

CREATE TABLE IF NOT EXISTS tournament_config (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  current_stage TEXT NOT NULL DEFAULT 'group',
  group_stage_done INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
