CREATE DATABASE IF NOT EXISTS worldcup2026 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE worldcup2026;

CREATE TABLE IF NOT EXISTS groups_table (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  group_name VARCHAR(10) NOT NULL,
  primary_color VARCHAR(20) NOT NULL DEFAULT '#FFFFFF',
  secondary_color VARCHAR(20) NOT NULL DEFAULT '#000000',
  confederation VARCHAR(20) NOT NULL DEFAULT 'UEFA',
  flag_emoji VARCHAR(10) NOT NULL DEFAULT '🏳️',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS players (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  team_id INT NOT NULL,
  position ENUM('GK','DEF','MID','FWD') NOT NULL,
  shirt_number INT NOT NULL DEFAULT 0,
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS matches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  team_a INT NOT NULL,
  team_b INT NOT NULL,
  score_a INT NOT NULL DEFAULT 0,
  score_b INT NOT NULL DEFAULT 0,
  stage ENUM('group','knockout') NOT NULL DEFAULT 'group',
  round_name VARCHAR(50) DEFAULT NULL,
  played TINYINT(1) NOT NULL DEFAULT 0,
  extra_time TINYINT(1) NOT NULL DEFAULT 0,
  penalties TINYINT(1) NOT NULL DEFAULT 0,
  penalty_score_a INT DEFAULT NULL,
  penalty_score_b INT DEFAULT NULL,
  match_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (team_a) REFERENCES teams(id),
  FOREIGN KEY (team_b) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS standings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  group_name VARCHAR(10) NOT NULL,
  team_id INT NOT NULL,
  points INT NOT NULL DEFAULT 0,
  played INT NOT NULL DEFAULT 0,
  won INT NOT NULL DEFAULT 0,
  drawn INT NOT NULL DEFAULT 0,
  lost INT NOT NULL DEFAULT 0,
  goals_for INT NOT NULL DEFAULT 0,
  goals_against INT NOT NULL DEFAULT 0,
  goal_difference INT GENERATED ALWAYS AS (goals_for - goals_against) STORED,
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  UNIQUE KEY unique_standing (group_name, team_id)
);

CREATE TABLE IF NOT EXISTS tournament_config (
  id INT AUTO_INCREMENT PRIMARY KEY,
  current_stage VARCHAR(50) NOT NULL DEFAULT 'group',
  group_stage_done TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
